CREATE SCHEMA pgkv;

CREATE TABLE pgkv.store(
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE OR REPLACE FUNCTION pgkv.set(TEXT, TEXT)
RETURNS VOID AS 'pgkv', 'pgkv_set'
LANGUAGE C STRICT;
GRANT EXECUTE ON FUNCTION pgkv.set(TEXT, TEXT) TO PUBLIC;

CREATE OR REPLACE FUNCTION pgkv.get(TEXT)
RETURNS TEXT AS 'pgkv', 'pgkv_get'
LANGUAGE C STRICT;
GRANT EXECUTE ON FUNCTION pgkv.get(TEXT) TO PUBLIC;

CREATE OR REPLACE FUNCTION pgkv.del(TEXT)
RETURNS VOID AS 'pgkv', 'pgkv_del'
LANGUAGE C STRICT;
GRANT EXECUTE ON FUNCTION pgkv.del(TEXT) TO PUBLIC;

CREATE OR REPLACE FUNCTION pgkv.list(TEXT)
RETURNS TEXT AS 'pgkv', 'pgkv_list'
LANGUAGE C STRICT;
GRANT EXECUTE ON FUNCTION pgkv.list(TEXT) TO PUBLIC;

CREATE OR REPLACE FUNCTION pgkv.list()
RETURNS TEXT AS 'pgkv', 'pgkv_list'
LANGUAGE C STRICT;
GRANT EXECUTE ON FUNCTION pgkv.list() TO PUBLIC;
